import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import styles from '../styles/Home.module.css'
import {appEndereco} from '../lib/variaveis_globais.js'

export default function Home({ list }) {
  return (
    <div className={styles.container}>
      <Head>
        <title>Catalogo de filmes</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <h1 className={styles.title}>
          Filmes em destaque
        </h1>
        <Link href="/busca">Search</Link>
        <ul>
          {list.map(item => (
            <li>
              <a href={`/movie/${item.id}`}>
                <img src={`http://image.tmdb.org/t/p/original${item.poster_path}`} width="150" /><br />
                {item.title}
              </a>
            </li>
          ))}
        </ul>

      </main>
    </div>
  )
}

export async function getServerSideProps() {

  const retorno = await fetch(`${appEndereco}/api/trending`)
  const json = await retorno.json()

  return {
    props: {
      list: json.list
    }
  }
}
